language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
install:
  - yarn install
  - yarn lernabootstrap
  - yarn lernabuild
script:
  - yarn deploy